### ISSUE TITLE
Issue when running with source vs. Nuget

### ISSUE THREAD

**Issue by stevewgh** [mauroservienti/NServiceBus.IntegrationTesting#122]
We have failing messages in our test and when we inspect the exception attached to the failing message(s) in the IntegrationScenarioContext.FailedMessages dictionary we see this:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.IntegrationTesting.InterceptInvokedHandlers.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext() in /_/src/NServiceBus.Core/Pipeline/Incoming/LoadHandlersConnector.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ScheduledTaskHandlingBehavior.<Invoke>d__1.MoveNext() in /_/src/NServiceBus.Core/Scheduling/ScheduledTaskHandlingBehavior.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NServiceBus.DeserializeMessageConnector.<Invoke>d__1.MoveNext() in /_/src/NServiceBus.Core/Pipeline/Incoming/DeserializeMessageConnector.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.InvokeAuditPipelineBehavior.<Invoke>d__1.MoveNext() in /_/src/NServiceBus.Core/Audit/InvokeAuditPipelineBehavior.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext() in /_/src/NServiceBus.Core/Performance/Statistics/ProcessingStatisticsBehavior.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageConnector.<Invoke>d__1.MoveNext() in /_/src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageConnector.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AcceptanceTesting.Support.CaptureExceptionBehavior.<Invoke>d__1.MoveNext() in /_/src/NServiceBus.AcceptanceTesting/Support/CaptureExceptionBehavior.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in /_/src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs:line 45

```

However, if we replace the Nuget reference with a project reference to the NServiceBus.Integration project instead we actually see the real exception which is a problem within our endpoint handler. So it appears that this is a bug that has been fixed in the latest version of the source but hasn't been published to Nuget? 

Does that sound correct?

**Comment by mauroservienti** [comment]
@stevewgh thanks for raising this. I'm not sure I fully understand the scenario you're describing. Before diving into that, the latest release is `0.0.6` (October 17), since then the only things that changed are mostly testing dependencies. However, `0.0.6` depends on `NServiceBus` and `NServiceBus.AcceptanceTesting` `>= 7.4.3`, but the latest source code depends on `>= 7.4.4`

Which version of NServiceBus are you using?

**Comment by stevewgh** [comment]
@mauroservienti I've checked and we are using the latest 7.4.4 version of NSB. 

I think I've found the issue though, if I get the source at commit ceed0b6cf0da6315ce26b1e664e1ad340e983ec5 (which appears to be tagged 0.6.0) then I can see the issue in my own tests (the Object Reference Not Set exception seen above). However, if I get the source at commit 6e440b1eaa4739feca32e33b2f4fe7d7b2313a4d then I see the actual real reason for test failure, so the changes in 6e440b1eaa4739feca32e33b2f4fe7d7b2313a4d appear to have fixed the problem but they aren't in the latest nuget.

Hopefully that makes a bit more sense.

**Comment by mauroservienti** [comment]
Ah, you're right 😄 
When I released `0.6.0` I selected the wrong commit, the one from merging #104, when creating the tag. I should have selected the one from #107. I'll release `0.0.7` in a bit.

**Comment by mauroservienti** [comment]
I released [0.7.0](https://github.com/mauroservienti/NServiceBus.IntegrationTesting/releases/tag/0.7.0) right now. It's on nuget https://www.nuget.org/packages/NServiceBus.IntegrationTesting/0.7.0

Let me know if it fixes the problem.

**Comment by stevewgh** [comment]
That works perfectly, thank you for the fast turn around!

**Comment by mauroservienti** [comment]
Thank you for the feedback. Closing.
